# Filtering DataFrames and Series

In [2]:
import pandas as pd

We are going to use a dataset that has Airbnb listing information in Lisbon.

In [6]:
df = pd.read_csv('data/airbnb.csv', index_col='room_id')
df

,host_id,room_type,neighborhood,reviews,overall_satisfaction,accommodates,bedrooms,price
room_id,,,,,,,,
6499,14455,Entire home/apt,Belém,8,5.0,2,1.0,57.0
17031,66015,Entire home/apt,Alvalade,0,0.0,2,1.0,46.0
25659,107347,Entire home/apt,Santa Maria Maior,63,5.0,3,1.0,69.0
29248,125768,Entire home/apt,Santa Maria Maior,225,4.5,4,1.0,58.0
29396,126415,Entire home/apt,Santa Maria Maior,132,5.0,4,1.0,67.0
29720,128075,Entire home/apt,Estrela,14,5.0,16,9.0,1154.0
29872,128698,Entire home/apt,Alcântara,25,5.0,2,1.0,75.0
29891,128792,Entire home/apt,Misericórdia,28,5.0,3,1.0,49.0
29915,128890,Entire home/apt,Avenidas Novas,28,4.5,3,1.0,58.0
33312,144398,Entire home/apt,Misericórdia,24,4.5,4,1.0,66.0
33348,144484,Private room,Lumiar,2,0.0,6,1.0,46.0
34783,149980,Private room,Estrela,0,0.0,1,1.0,54.0
34977,146695,Entire home/apt,Santa Maria Maior,54,4.5,6,2.0,60.0
40817,176410,Entire home/apt,Misericórdia,229,4.5,2,1.0,52.0
42172,184400,Entire home/apt,Santa Maria Maior,45,4.5,6,2.0,138.0
42519,136230,Entire home/apt,Misericórdia,79,4.5,3,1.0,87.0
44043,192830,Entire home/apt,Santa Maria Maior,316,5.0,7,3.0,80.0
46567,208343,Private room,Avenidas Novas,3,5.0,2,1.0,39.0
47717,217058,Entire home/apt,Santa Maria Maior,70,4.5,3,1.0,57.0
50108,229376,Entire home/apt,Estrela,33,4.5,4,1.0,69.0
55116,259744,Private room,Avenidas Novas,1,0.0,2,2.0,68.0
56906,270457,Entire home/apt,São Vicente,86,4.5,3,1.0,52.0
57850,276092,Entire home/apt,Estrela,52,4.5,3,2.0,70.0
59227,184400,Entire home/apt,Misericórdia,25,4.5,7,3.0,138.0
65553,320407,Entire home/apt,Campo de Ourique,102,4.5,2,1.0,58.0
65878,322145,Entire home/apt,Misericórdia,51,5.0,4,1.0,76.0
72807,378525,Private room,Alvalade,1,0.0,1,1.0,29.0
73764,154341,Entire home/apt,Santo António,18,4.5,2,1.0,64.0
75171,184400,Entire home/apt,Estrela,19,4.5,5,2.0,115.0
77130,412702,Entire home/apt,Misericórdia,74,4.5,3,0.0,52.0
...,...,...,...,...,...,...,...,...
19360001,26864642,Private room,Arroios,0,0.0,6,3.0,33.0
19361749,127589264,Entire home/apt,São Domingos de Benfica,0,0.0,4,2.0,69.0
19362076,88928860,Entire home/apt,Penha de França,0,0.0,4,2.0,104.0
19362417,28225140,Private room,Arroios,0,0.0,2,1.0,29.0
19363100,88928860,Private room,Penha de França,0,0.0,2,1.0,46.0
19368183,14317794,Entire home/apt,Misericórdia,0,0.0,4,1.0,104.0
19369538,114388582,Entire home/apt,Misericórdia,0,0.0,4,2.0,65.0
19370050,14317794,Entire home/apt,Misericórdia,0,0.0,3,2.0,109.0
19370165,114388582,Entire home/apt,Santo António,0,0.0,4,2.0,58.0
19370278,135784989,Entire home/apt,Santa Maria Maior,0,0.0,4,2.0,184.0
19370578,131185696,Entire home/apt,Alcântara,0,0.0,5,2.0,71.0
19370769,135787783,Entire home/apt,Santa Maria Maior,0,0.0,4,2.0,176.0
19373212,131185696,Entire home/apt,Alcântara,0,0.0,4,2.0,75.0
19376122,119457178,Entire home/apt,Ajuda,0,0.0,5,2.0,64.0
19379554,104083974,Entire home/apt,Belém,0,0.0,4,1.0,69.0
19379856,12723358,Entire home/apt,Parque das Nações,0,0.0,2,1.0,80.0
19380177,104083974,Entire home/apt,Belém,0,0.0,6,2.0,69.0
19380414,85047832,Entire home/apt,São Vicente,0,0.0,2,0.0,52.0
19380457,104083974,Entire home/apt,Belém,0,0.0,6,3.0,93.0
19381136,131185696,Entire home/apt,Alcântara,0,0.0,3,1.0,48.0
19383103,48844725,Entire home/apt,Estrela,0,0.0,4,2.0,84.0
19383615,100924999,Entire home/apt,Parque das Nações,0,0.0,4,1.0,52.0
19385945,135895465,Entire home/apt,São Domingos de Benfica,0,0.0,4,2.0,64.0
19386235,55922649,Entire home/apt,Santa Maria Maior,0,0.0,4,1.0,87.0
19386898,95929866,Entire home/apt,Arroios,0,0.0,3,1.0,91.0
19388006,135915593,Entire home/apt,São Vicente,0,0.0,6,3.0,415.0
19393935,5376796,Entire home/apt,Santa Maria Maior,0,0.0,3,1.0,50.0
19396300,6115933,Entire home/apt,Santo António,0,0.0,6,4.0,138.0
19397373,97139334,Entire home/apt,São Vicente,0,0.0,4,1.0,56.0
19400722,28219108,Entire home/apt,Areeiro,0,0.0,5,3.0,75.0

In [5]:
df.shape

(13232, 8)

In [4]:
df.head()

,host_id,room_type,neighborhood,reviews,overall_satisfaction,accommodates,bedrooms,price
room_id,,,,,,,,
6499,14455,Entire home/apt,Belém,8,5.0,2,1.0,57.0
17031,66015,Entire home/apt,Alvalade,0,0.0,2,1.0,46.0
25659,107347,Entire home/apt,Santa Maria Maior,63,5.0,3,1.0,69.0
29248,125768,Entire home/apt,Santa Maria Maior,225,4.5,4,1.0,58.0
29396,126415,Entire home/apt,Santa Maria Maior,132,5.0,4,1.0,67.0

# Selecting rows

## Selecting rows by their position - iloc

We use the function [iloc](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.iloc.html) to select specific rows on a Data Frame (regardless of the index).

With `iloc` we select rows regarding their row number, starting at 0.

In [5]:
df.iloc[0]

host_id                           14455
room_type               Entire home/apt
neighborhood                      Belém
reviews                               8
overall_satisfaction                  5
accommodates                          2
bedrooms                              1
price                                57
Name: 6499, dtype: object

In [6]:
type(df.iloc[0])

pandas.core.series.Series

If we want the selection to be a dataframe (instead of a Series), we can use double brackets `[[]]`

In [7]:
df.iloc[[0]]

,host_id,room_type,neighborhood,reviews,overall_satisfaction,accommodates,bedrooms,price
room_id,,,,,,,,
6499,14455,Entire home/apt,Belém,8,5.0,2,1.0,57.0

We can select multiple rows at once:

In [8]:
df.iloc[[0, 3,5]]

,host_id,room_type,neighborhood,reviews,overall_satisfaction,accommodates,bedrooms,price
room_id,,,,,,,,
6499,14455,Entire home/apt,Belém,8,5.0,2,1.0,57.0
29248,125768,Entire home/apt,Santa Maria Maior,225,4.5,4,1.0,58.0
29720,128075,Entire home/apt,Estrela,14,5.0,16,9.0,1154.0

Or use slices like with arrays:

In [9]:
df.iloc[2:10]

,host_id,room_type,neighborhood,reviews,overall_satisfaction,accommodates,bedrooms,price
room_id,,,,,,,,
25659,107347,Entire home/apt,Santa Maria Maior,63,5.0,3,1.0,69.0
29248,125768,Entire home/apt,Santa Maria Maior,225,4.5,4,1.0,58.0
29396,126415,Entire home/apt,Santa Maria Maior,132,5.0,4,1.0,67.0
29720,128075,Entire home/apt,Estrela,14,5.0,16,9.0,1154.0
29872,128698,Entire home/apt,Alcântara,25,5.0,2,1.0,75.0
29891,128792,Entire home/apt,Misericórdia,28,5.0,3,1.0,49.0
29915,128890,Entire home/apt,Avenidas Novas,28,4.5,3,1.0,58.0
33312,144398,Entire home/apt,Misericórdia,24,4.5,4,1.0,66.0

## Selecting rows by their index value - loc

* With [.loc](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.loc.html) we can select rows based on their index value.

Since we have set the dataframe index as the Airbnb listing, we can select a specific room based on its id, for example, the listing 10186098.

In [10]:
df.loc[10186098]

host_id                            520897
room_type                 Entire home/apt
neighborhood            Santa Maria Maior
reviews                                 2
overall_satisfaction                    0
accommodates                            4
bedrooms                                1
price                                  64
Name: 10186098, dtype: object

Selecting an index value that doesnt exist wil fail like it would do with a dictionary

In [11]:
df.loc[[5]]

KeyError: 'None of [[5]] are in the [index]'

Same as with .iloc, we can select multiple values at once.

In [12]:
df.loc[[29872, 19188572, 4612503 ]]

,host_id,room_type,neighborhood,reviews,overall_satisfaction,accommodates,bedrooms,price
room_id,,,,,,,,
29872,128698,Entire home/apt,Alcântara,25,5.0,2,1.0,75.0
19188572,134216988,Private room,Arroios,0,0.0,4,1.0,58.0
4612503,22078192,Entire home/apt,Santa Maria Maior,12,5.0,3,1.0,113.0

We can use a boolean array (a list of True and False) to select multiple rows with loc, this is called a **mask**.

In [13]:
df.loc[[True, True, False, True]]

,host_id,room_type,neighborhood,reviews,overall_satisfaction,accommodates,bedrooms,price
room_id,,,,,,,,
6499,14455,Entire home/apt,Belém,8,5.0,2,1.0,57.0
17031,66015,Entire home/apt,Alvalade,0,0.0,2,1.0,46.0
29248,125768,Entire home/apt,Santa Maria Maior,225,4.5,4,1.0,58.0

We see we have selected rows 1,2 and 4 of the dataframe

In [14]:
df.head()

,host_id,room_type,neighborhood,reviews,overall_satisfaction,accommodates,bedrooms,price
room_id,,,,,,,,
6499,14455,Entire home/apt,Belém,8,5.0,2,1.0,57.0
17031,66015,Entire home/apt,Alvalade,0,0.0,2,1.0,46.0
25659,107347,Entire home/apt,Santa Maria Maior,63,5.0,3,1.0,69.0
29248,125768,Entire home/apt,Santa Maria Maior,225,4.5,4,1.0,58.0
29396,126415,Entire home/apt,Santa Maria Maior,132,5.0,4,1.0,67.0

## Column Selection

## Selecting columns by their name

We can select columns using dot notation **(as long as the column names dont have spaces or non alphanumerical characters on them)**

In [15]:
df.room_type

room_id
6499        Entire home/apt
17031       Entire home/apt
25659       Entire home/apt
29248       Entire home/apt
29396       Entire home/apt
29720       Entire home/apt
29872       Entire home/apt
29891       Entire home/apt
29915       Entire home/apt
33312       Entire home/apt
33348          Private room
34783          Private room
34977       Entire home/apt
40817       Entire home/apt
42172       Entire home/apt
42519       Entire home/apt
44043       Entire home/apt
46567          Private room
47717       Entire home/apt
50108       Entire home/apt
55116          Private room
56906       Entire home/apt
57850       Entire home/apt
59227       Entire home/apt
65553       Entire home/apt
65878       Entire home/apt
72807          Private room
73764       Entire home/apt
75171       Entire home/apt
77130       Entire home/apt
                 ...
19360001       Private room
19361749    Entire home/apt
19362076    Entire home/apt
19362417       Private room
19363100       Private room
19368183    Entire home/apt
19369538    Entire home/apt
19370050    Entire home/apt
19370165    Entire home/apt
19370278    Entire home/apt
19370578    Entire home/apt
19370769    Entire home/apt
19373212    Entire home/apt
19376122    Entire home/apt
19379554    Entire home/apt
19379856    Entire home/apt
19380177    Entire home/apt
19380414    Entire home/apt
19380457    Entire home/apt
19381136    Entire home/apt
19383103    Entire home/apt
19383615    Entire home/apt
19385945    Entire home/apt
19386235    Entire home/apt
19386898    Entire home/apt
19388006    Entire home/apt
19393935    Entire home/apt
19396300    Entire home/apt
19397373    Entire home/apt
19400722    Entire home/apt
Name: room_type, Length: 13232, dtype: object

Which is the same as doing:

In [16]:
df['room_type']

room_id
6499        Entire home/apt
17031       Entire home/apt
25659       Entire home/apt
29248       Entire home/apt
29396       Entire home/apt
29720       Entire home/apt
29872       Entire home/apt
29891       Entire home/apt
29915       Entire home/apt
33312       Entire home/apt
33348          Private room
34783          Private room
34977       Entire home/apt
40817       Entire home/apt
42172       Entire home/apt
42519       Entire home/apt
44043       Entire home/apt
46567          Private room
47717       Entire home/apt
50108       Entire home/apt
55116          Private room
56906       Entire home/apt
57850       Entire home/apt
59227       Entire home/apt
65553       Entire home/apt
65878       Entire home/apt
72807          Private room
73764       Entire home/apt
75171       Entire home/apt
77130       Entire home/apt
                 ...
19360001       Private room
19361749    Entire home/apt
19362076    Entire home/apt
19362417       Private room
19363100       Private room
19368183    Entire home/apt
19369538    Entire home/apt
19370050    Entire home/apt
19370165    Entire home/apt
19370278    Entire home/apt
19370578    Entire home/apt
19370769    Entire home/apt
19373212    Entire home/apt
19376122    Entire home/apt
19379554    Entire home/apt
19379856    Entire home/apt
19380177    Entire home/apt
19380414    Entire home/apt
19380457    Entire home/apt
19381136    Entire home/apt
19383103    Entire home/apt
19383615    Entire home/apt
19385945    Entire home/apt
19386235    Entire home/apt
19386898    Entire home/apt
19388006    Entire home/apt
19393935    Entire home/apt
19396300    Entire home/apt
19397373    Entire home/apt
19400722    Entire home/apt
Name: room_type, Length: 13232, dtype: object

When we select one column we receive a pd.Series, we can use double brackets to select multiple columns (if we select multiple columns we will always receive a dataframe).

In [17]:
df[["room_type", "price"]].head()

               room_type  price
room_id
6499     Entire home/apt   57.0
17031    Entire home/apt   46.0
25659    Entire home/apt   69.0
29248    Entire home/apt   58.0
29396    Entire home/apt   67.0

We can always select columns with loc

In [18]:
df.loc[:, "room_type"][:10]

room_id
6499     Entire home/apt
17031    Entire home/apt
25659    Entire home/apt
29248    Entire home/apt
29396    Entire home/apt
29720    Entire home/apt
29872    Entire home/apt
29891    Entire home/apt
29915    Entire home/apt
33312    Entire home/apt
Name: room_type, dtype: object

The index doesnt have to be unique, for example we can set the neighbourhood as the index.

In [19]:
df.head()

,host_id,room_type,neighborhood,reviews,overall_satisfaction,accommodates,bedrooms,price
room_id,,,,,,,,
6499,14455,Entire home/apt,Belém,8,5.0,2,1.0,57.0
17031,66015,Entire home/apt,Alvalade,0,0.0,2,1.0,46.0
25659,107347,Entire home/apt,Santa Maria Maior,63,5.0,3,1.0,69.0
29248,125768,Entire home/apt,Santa Maria Maior,225,4.5,4,1.0,58.0
29396,126415,Entire home/apt,Santa Maria Maior,132,5.0,4,1.0,67.0

In [20]:
df = df.set_index("neighborhood")

In [21]:
df.loc["Belém"].head()

,host_id,room_type,reviews,overall_satisfaction,accommodates,bedrooms,price
neighborhood,,,,,,,
Belém,14455,Entire home/apt,8,5.0,2,1.0,57.0
Belém,992647,Entire home/apt,54,4.0,2,1.0,45.0
Belém,2083563,Private room,2,0.0,2,1.0,127.0
Belém,2341627,Entire home/apt,64,4.5,4,1.0,67.0
Belém,3168004,Entire home/apt,57,4.5,3,2.0,46.0

We set back the index to `host_id`, we need to use the argument `drop=False` so pandas doesnt remove the original index

In [22]:
df = df.set_index("host_id", drop=False)

## Mask

The function ([Mask](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.mask.html)) allows us to "hide" parts of a dataframe that match a certain condition.

In [23]:
df.mask(df.overall_satisfaction == 5.0)

,host_id,room_type,reviews,overall_satisfaction,accommodates,bedrooms,price
host_id,,,,,,,
14455,NaN,NaN,NaN,NaN,NaN,NaN,NaN
66015,66015.0,Entire home/apt,0.0,0.0,2.0,1.0,46.0
107347,NaN,NaN,NaN,NaN,NaN,NaN,NaN
125768,125768.0,Entire home/apt,225.0,4.5,4.0,1.0,58.0
126415,NaN,NaN,NaN,NaN,NaN,NaN,NaN
128075,NaN,NaN,NaN,NaN,NaN,NaN,NaN
128698,NaN,NaN,NaN,NaN,NaN,NaN,NaN
128792,NaN,NaN,NaN,NaN,NaN,NaN,NaN
128890,128890.0,Entire home/apt,28.0,4.5,3.0,1.0,58.0
144398,144398.0,Entire home/apt,24.0,4.5,4.0,1.0,66.0
144484,144484.0,Private room,2.0,0.0,6.0,1.0,46.0
149980,149980.0,Private room,0.0,0.0,1.0,1.0,54.0
146695,146695.0,Entire home/apt,54.0,4.5,6.0,2.0,60.0
176410,176410.0,Entire home/apt,229.0,4.5,2.0,1.0,52.0
184400,184400.0,Entire home/apt,45.0,4.5,6.0,2.0,138.0
136230,136230.0,Entire home/apt,79.0,4.5,3.0,1.0,87.0
192830,NaN,NaN,NaN,NaN,NaN,NaN,NaN
208343,NaN,NaN,NaN,NaN,NaN,NaN,NaN
217058,217058.0,Entire home/apt,70.0,4.5,3.0,1.0,57.0
229376,229376.0,Entire home/apt,33.0,4.5,4.0,1.0,69.0
259744,259744.0,Private room,1.0,0.0,2.0,2.0,68.0
270457,270457.0,Entire home/apt,86.0,4.5,3.0,1.0,52.0
276092,276092.0,Entire home/apt,52.0,4.5,3.0,2.0,70.0
184400,184400.0,Entire home/apt,25.0,4.5,7.0,3.0,138.0
320407,320407.0,Entire home/apt,102.0,4.5,2.0,1.0,58.0
322145,NaN,NaN,NaN,NaN,NaN,NaN,NaN
378525,378525.0,Private room,1.0,0.0,1.0,1.0,29.0
154341,154341.0,Entire home/apt,18.0,4.5,2.0,1.0,64.0
184400,184400.0,Entire home/apt,19.0,4.5,5.0,2.0,115.0
412702,412702.0,Entire home/apt,74.0,4.5,3.0,0.0,52.0
...,...,...,...,...,...,...,...
26864642,26864642.0,Private room,0.0,0.0,6.0,3.0,33.0
127589264,127589264.0,Entire home/apt,0.0,0.0,4.0,2.0,69.0
88928860,88928860.0,Entire home/apt,0.0,0.0,4.0,2.0,104.0
28225140,28225140.0,Private room,0.0,0.0,2.0,1.0,29.0
88928860,88928860.0,Private room,0.0,0.0,2.0,1.0,46.0
14317794,14317794.0,Entire home/apt,0.0,0.0,4.0,1.0,104.0
114388582,114388582.0,Entire home/apt,0.0,0.0,4.0,2.0,65.0
14317794,14317794.0,Entire home/apt,0.0,0.0,3.0,2.0,109.0
114388582,114388582.0,Entire home/apt,0.0,0.0,4.0,2.0,58.0
135784989,135784989.0,Entire home/apt,0.0,0.0,4.0,2.0,184.0
131185696,131185696.0,Entire home/apt,0.0,0.0,5.0,2.0,71.0
135787783,135787783.0,Entire home/apt,0.0,0.0,4.0,2.0,176.0
131185696,131185696.0,Entire home/apt,0.0,0.0,4.0,2.0,75.0
119457178,119457178.0,Entire home/apt,0.0,0.0,5.0,2.0,64.0
104083974,104083974.0,Entire home/apt,0.0,0.0,4.0,1.0,69.0
12723358,12723358.0,Entire home/apt,0.0,0.0,2.0,1.0,80.0
104083974,104083974.0,Entire home/apt,0.0,0.0,6.0,2.0,69.0
85047832,85047832.0,Entire home/apt,0.0,0.0,2.0,0.0,52.0
104083974,104083974.0,Entire home/apt,0.0,0.0,6.0,3.0,93.0
131185696,131185696.0,Entire home/apt,0.0,0.0,3.0,1.0,48.0
48844725,48844725.0,Entire home/apt,0.0,0.0,4.0,2.0,84.0
100924999,100924999.0,Entire home/apt,0.0,0.0,4.0,1.0,52.0
135895465,135895465.0,Entire home/apt,0.0,0.0,4.0,2.0,64.0
55922649,55922649.0,Entire home/apt,0.0,0.0,4.0,1.0,87.0
95929866,95929866.0,Entire home/apt,0.0,0.0,3.0,1.0,91.0
135915593,135915593.0,Entire home/apt,0.0,0.0,6.0,3.0,415.0
5376796,5376796.0,Entire home/apt,0.0,0.0,3.0,1.0,50.0
6115933,6115933.0,Entire home/apt,0.0,0.0,6.0,4.0,138.0
97139334,97139334.0,Entire home/apt,0.0,0.0,4.0,1.0,56.0
28219108,28219108.0,Entire home/apt,0.0,0.0,5.0,3.0,75.0

We see that the rows that dont match the condition appear as `NaN`, which stands for **Not a Number**, a standard way of saying *"there is no relevant data here"*. Pandas will usually ignore the NaNs.

## Where

On the other hand, [where](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.where.html) hides those rows that don't match the condition (where is the opposite of mask).

In [26]:
df = pd.read_csv('data/airbnb.csv')

In [27]:
df.where(df.overall_satisfaction == 5.0)

,room_id,host_id,room_type,neighborhood,reviews,overall_satisfaction,accommodates,bedrooms,price
0,6499.0,14455.0,Entire home/apt,Belém,8.0,5.0,2.0,1.0,57.0
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,25659.0,107347.0,Entire home/apt,Santa Maria Maior,63.0,5.0,3.0,1.0,69.0
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,29396.0,126415.0,Entire home/apt,Santa Maria Maior,132.0,5.0,4.0,1.0,67.0
5,29720.0,128075.0,Entire home/apt,Estrela,14.0,5.0,16.0,9.0,1154.0
6,29872.0,128698.0,Entire home/apt,Alcântara,25.0,5.0,2.0,1.0,75.0
7,29891.0,128792.0,Entire home/apt,Misericórdia,28.0,5.0,3.0,1.0,49.0
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,44043.0,192830.0,Entire home/apt,Santa Maria Maior,316.0,5.0,7.0,3.0,80.0
17,46567.0,208343.0,Private room,Avenidas Novas,3.0,5.0,2.0,1.0,39.0
18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,65878.0,322145.0,Entire home/apt,Misericórdia,51.0,5.0,4.0,1.0,76.0
26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
13202,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13203,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13204,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13205,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13206,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13207,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13208,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13209,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13210,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13211,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13212,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13213,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13214,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13215,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13216,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13217,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13218,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13219,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13220,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13221,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13222,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13223,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13224,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13225,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13226,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13227,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13228,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13229,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13230,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13231,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# Filtering with []

We can also filter by using brackets.
The difference between filtering with brackets and using `mask/where` is that with brackets we only receive a segment of the dataframe (less rows), while with `mask/where` we receive a dataframe with the same rows and index than the original one.

For example, we can filter the dataframe to see all the listings in `Belem`:

In [28]:
df.head()

,room_id,host_id,room_type,neighborhood,reviews,overall_satisfaction,accommodates,bedrooms,price
0,6499,14455,Entire home/apt,Belém,8,5.0,2,1.0,57.0
1,17031,66015,Entire home/apt,Alvalade,0,0.0,2,1.0,46.0
2,25659,107347,Entire home/apt,Santa Maria Maior,63,5.0,3,1.0,69.0
3,29248,125768,Entire home/apt,Santa Maria Maior,225,4.5,4,1.0,58.0
4,29396,126415,Entire home/apt,Santa Maria Maior,132,5.0,4,1.0,67.0

In [29]:
df.where(df.neighborhood=="Belém").shape

(13232, 9)

If we use brackets, the dataframe we get is smaller

In [30]:
df[df.neighborhood == 'Belém']

,room_id,host_id,room_type,neighborhood,reviews,overall_satisfaction,accommodates,bedrooms,price
0,6499,14455,Entire home/apt,Belém,8,5.0,2,1.0,57.0
141,202654,992647,Entire home/apt,Belém,54,4.0,2,1.0,45.0
302,418945,2083563,Private room,Belém,2,0.0,2,1.0,127.0
357,472183,2341627,Entire home/apt,Belém,64,4.5,4,1.0,67.0
520,635674,3168004,Entire home/apt,Belém,57,4.5,3,2.0,46.0
661,758927,3999677,Entire home/apt,Belém,10,5.0,4,2.0,69.0
685,783766,4132746,Private room,Belém,49,4.5,3,1.0,22.0
694,787134,3634413,Entire home/apt,Belém,48,4.0,5,3.0,58.0
720,820798,1756107,Entire home/apt,Belém,4,4.5,4,1.0,68.0
772,862418,4520597,Entire home/apt,Belém,84,4.5,4,1.0,46.0
831,935478,1029524,Entire home/apt,Belém,33,4.5,4,1.0,46.0
859,964480,3168004,Entire home/apt,Belém,60,4.5,4,2.0,52.0
864,977488,3680667,Entire home/apt,Belém,15,5.0,4,1.0,69.0
1006,1175357,2644971,Entire home/apt,Belém,32,5.0,3,2.0,55.0
1118,1327544,7204661,Private room,Belém,2,0.0,2,1.0,144.0
1158,1378048,3634413,Entire home/apt,Belém,47,4.5,7,3.0,87.0
1190,1427168,7649262,Private room,Belém,10,5.0,2,1.0,49.0
1243,1506789,8048828,Entire home/apt,Belém,122,5.0,4,1.0,58.0
1271,1550751,4132746,Entire home/apt,Belém,40,4.5,8,3.0,44.0
1351,1724077,8810620,Entire home/apt,Belém,105,4.5,4,2.0,64.0
1352,1725052,8810620,Entire home/apt,Belém,104,4.5,5,3.0,64.0
1406,1803927,9456814,Entire home/apt,Belém,0,0.0,6,3.0,173.0
1551,2127428,8810620,Entire home/apt,Belém,17,5.0,9,5.0,184.0
1701,2487363,12123730,Entire home/apt,Belém,72,4.5,6,2.0,52.0
1756,2590441,10766652,Entire home/apt,Belém,89,5.0,4,2.0,75.0
1767,2608025,9456814,Entire home/apt,Belém,0,0.0,10,2.0,288.0
1769,2612285,11926451,Private room,Belém,23,4.0,2,1.0,18.0
1771,2623665,2990770,Entire home/apt,Belém,44,5.0,2,1.0,68.0
1772,2623683,776635,Entire home/apt,Belém,7,5.0,10,3.0,115.0
1818,2699381,8911887,Entire home/apt,Belém,1,0.0,4,1.0,78.0
...,...,...,...,...,...,...,...,...,...
11867,18213525,19254511,Entire home/apt,Belém,0,0.0,2,1.0,85.0
11881,18227246,125892685,Entire home/apt,Belém,1,0.0,4,2.0,79.0
11910,18260651,37385021,Entire home/apt,Belém,11,4.5,4,1.0,29.0
11933,18271919,125011727,Entire home/apt,Belém,2,0.0,4,1.0,46.0
11999,18317275,9618517,Private room,Belém,0,0.0,3,1.0,87.0
12181,18461428,115620308,Private room,Belém,2,0.0,10,2.0,208.0
12193,18476060,115620308,Private room,Belém,2,0.0,5,0.0,93.0
12194,18476206,115620308,Private room,Belém,0,0.0,5,0.0,84.0
12202,18483915,2528842,Entire home/apt,Belém,0,0.0,2,1.0,91.0
12227,18512183,651801,Entire home/apt,Belém,0,0.0,4,1.0,53.0
12281,18561077,3695889,Private room,Belém,0,0.0,2,1.0,58.0
12298,18578066,128986153,Entire home/apt,Belém,4,5.0,4,1.0,58.0
12447,18702996,72308704,Entire home/apt,Belém,0,0.0,3,1.0,58.0
12481,18735274,128909464,Entire home/apt,Belém,2,0.0,5,3.0,52.0
12492,18745670,121873936,Entire home/apt,Belém,1,0.0,3,1.0,41.0
12649,18892988,25020268,Entire home/apt,Belém,0,0.0,3,1.0,58.0
12680,18928035,39219982,Entire home/apt,Belém,0,0.0,4,2.0,80.0
12722,18965299,10463670,Entire home/apt,Belém,0,0.0,4,1.0,138.0
12727,18969850,1185103,Entire home/apt,Belém,3,4.5,6,2.0,68.0
12763,18998643,132541338,Entire home/apt,Belém,0,0.0,6,2.0,126.0
12808,19034170,62521369,Entire home/apt,Belém,5,5.0,4,1.0,85.0
12809,19036207,132541338,Entire home/apt,Belém,0,0.0,4,1.0,97.0
13078,19228230,134610991,Entire home/apt,Belém,0,0.0,3,0.0,80.0
13106,19260440,48194126,Private room,Belém,0,0.0,2,1.0,27.0
13119,19269358,53334020,Entire home/apt,Belém,0,0.0,4,1.0,75.0
13128,19282613,1343572,Entire home/apt,Belém,0,0.0,3,2.0,93.0
13131,19285913,130280879,Entire home/apt,Belém,0,0.0,6,2.0,68.0
13216,19379554,104083974,Entire home/apt,Belém,0,0.0,4,1.0,69.0
13218,19380177,104083974,Entire home/apt,Belém,0,0.0,6,2.0,69.0
13220,19380457,104083974,Entire home/apt,Belém,0,0.0,6,3.0,93.0

In [31]:
df[df.neighborhood == 'Belém'].shape

(254, 9)

We can select the inverse of a condition if we put `~` in front of it.

For example, to select all listings that are not in Belem, we can do this:

In [32]:
df[~(df.neighborhood ==  "Belém")].shape

(12978, 9)

# Multiple Selection

We can filter a dataframe based on multiple conditions.

We can select rows that match multiple conditions by concatenating the conditions with `&`.

For example, if we want those listings in Belém with more than 3 bedrooms:

In [33]:
df[(df.neighborhood == 'Belém') & (df.bedrooms > 3)]

,room_id,host_id,room_type,neighborhood,reviews,overall_satisfaction,accommodates,bedrooms,price
1551,2127428,8810620,Entire home/apt,Belém,17,5.0,9,5.0,184.0
3671,5737018,29744618,Entire home/apt,Belém,46,4.5,10,4.0,128.0
4444,6884183,11926451,Entire home/apt,Belém,1,0.0,10,5.0,138.0
5679,9522737,46064752,Entire home/apt,Belém,27,5.0,8,4.0,78.0
9314,15272166,17263208,Entire home/apt,Belém,1,0.0,6,4.0,288.0
10825,17228964,101182323,Entire home/apt,Belém,2,0.0,16,7.0,260.0

Same way, we can select rows that match one condition OR the other with the pipe (`|`)

In [34]:
df[(df.neighborhood == "Belém") | (df.neighborhood == "Benfica")]

,room_id,host_id,room_type,neighborhood,reviews,overall_satisfaction,accommodates,bedrooms,price
0,6499,14455,Entire home/apt,Belém,8,5.0,2,1.0,57.0
141,202654,992647,Entire home/apt,Belém,54,4.0,2,1.0,45.0
151,212915,1097919,Private room,Benfica,0,0.0,6,1.0,93.0
302,418945,2083563,Private room,Belém,2,0.0,2,1.0,127.0
357,472183,2341627,Entire home/apt,Belém,64,4.5,4,1.0,67.0
458,573313,2820083,Entire home/apt,Benfica,12,4.5,4,2.0,74.0
520,635674,3168004,Entire home/apt,Belém,57,4.5,3,2.0,46.0
661,758927,3999677,Entire home/apt,Belém,10,5.0,4,2.0,69.0
685,783766,4132746,Private room,Belém,49,4.5,3,1.0,22.0
694,787134,3634413,Entire home/apt,Belém,48,4.0,5,3.0,58.0
720,820798,1756107,Entire home/apt,Belém,4,4.5,4,1.0,68.0
772,862418,4520597,Entire home/apt,Belém,84,4.5,4,1.0,46.0
795,889052,1951343,Private room,Benfica,0,0.0,1,1.0,29.0
831,935478,1029524,Entire home/apt,Belém,33,4.5,4,1.0,46.0
859,964480,3168004,Entire home/apt,Belém,60,4.5,4,2.0,52.0
864,977488,3680667,Entire home/apt,Belém,15,5.0,4,1.0,69.0
1006,1175357,2644971,Entire home/apt,Belém,32,5.0,3,2.0,55.0
1118,1327544,7204661,Private room,Belém,2,0.0,2,1.0,144.0
1158,1378048,3634413,Entire home/apt,Belém,47,4.5,7,3.0,87.0
1190,1427168,7649262,Private room,Belém,10,5.0,2,1.0,49.0
1243,1506789,8048828,Entire home/apt,Belém,122,5.0,4,1.0,58.0
1271,1550751,4132746,Entire home/apt,Belém,40,4.5,8,3.0,44.0
1289,1573223,8178431,Entire home/apt,Benfica,17,4.5,4,2.0,64.0
1332,1670147,6362620,Private room,Benfica,32,4.5,6,1.0,46.0
1351,1724077,8810620,Entire home/apt,Belém,105,4.5,4,2.0,64.0
1352,1725052,8810620,Entire home/apt,Belém,104,4.5,5,3.0,64.0
1406,1803927,9456814,Entire home/apt,Belém,0,0.0,6,3.0,173.0
1551,2127428,8810620,Entire home/apt,Belém,17,5.0,9,5.0,184.0
1668,2399414,12260436,Private room,Benfica,1,0.0,2,1.0,23.0
1701,2487363,12123730,Entire home/apt,Belém,72,4.5,6,2.0,52.0
...,...,...,...,...,...,...,...,...,...
12194,18476206,115620308,Private room,Belém,0,0.0,5,0.0,84.0
12202,18483915,2528842,Entire home/apt,Belém,0,0.0,2,1.0,91.0
12227,18512183,651801,Entire home/apt,Belém,0,0.0,4,1.0,53.0
12234,18517941,128538019,Entire home/apt,Benfica,0,0.0,3,1.0,52.0
12281,18561077,3695889,Private room,Belém,0,0.0,2,1.0,58.0
12298,18578066,128986153,Entire home/apt,Belém,4,5.0,4,1.0,58.0
12447,18702996,72308704,Entire home/apt,Belém,0,0.0,3,1.0,58.0
12453,18705665,50870971,Private room,Benfica,6,5.0,2,1.0,23.0
12481,18735274,128909464,Entire home/apt,Belém,2,0.0,5,3.0,52.0
12492,18745670,121873936,Entire home/apt,Belém,1,0.0,3,1.0,41.0
12639,18879061,78574742,Private room,Benfica,3,5.0,2,1.0,18.0
12649,18892988,25020268,Entire home/apt,Belém,0,0.0,3,1.0,58.0
12665,18922110,33111699,Entire home/apt,Benfica,0,0.0,3,2.0,46.0
12680,18928035,39219982,Entire home/apt,Belém,0,0.0,4,2.0,80.0
12722,18965299,10463670,Entire home/apt,Belém,0,0.0,4,1.0,138.0
12727,18969850,1185103,Entire home/apt,Belém,3,4.5,6,2.0,68.0
12763,18998643,132541338,Entire home/apt,Belém,0,0.0,6,2.0,126.0
12808,19034170,62521369,Entire home/apt,Belém,5,5.0,4,1.0,85.0
12809,19036207,132541338,Entire home/apt,Belém,0,0.0,4,1.0,97.0
12910,19113703,129744959,Entire home/apt,Benfica,0,0.0,6,3.0,357.0
12952,19147754,133878061,Private room,Benfica,0,0.0,16,5.0,58.0
13078,19228230,134610991,Entire home/apt,Belém,0,0.0,3,0.0,80.0
13106,19260440,48194126,Private room,Belém,0,0.0,2,1.0,27.0
13119,19269358,53334020,Entire home/apt,Belém,0,0.0,4,1.0,75.0
13128,19282613,1343572,Entire home/apt,Belém,0,0.0,3,2.0,93.0
13131,19285913,130280879,Entire home/apt,Belém,0,0.0,6,2.0,68.0
13135,19299623,71859210,Entire home/apt,Benfica,0,0.0,5,2.0,102.0
13216,19379554,104083974,Entire home/apt,Belém,0,0.0,4,1.0,69.0
13218,19380177,104083974,Entire home/apt,Belém,0,0.0,6,2.0,69.0
13220,19380457,104083974,Entire home/apt,Belém,0,0.0,6,3.0,93.0

## Isnull/Notnull

Sometimes we simple want to select those rows there there are no null (`NaN`) values.

We can select rows where a column is null by doing `column.isnull()`.

In [35]:
df[df.overall_satisfaction.isnull()]

,room_id,host_id,room_type,neighborhood,reviews,overall_satisfaction,accommodates,bedrooms,price
1189,1424459,7665008,Entire home/apt,Misericórdia,63,NaN,8,4.0,104.0
2259,3112523,15814568,Entire home/apt,Misericórdia,1,NaN,3,1.0,69.0
3031,4460918,6317960,Entire home/apt,Arroios,75,NaN,4,1.0,40.0
3574,5569600,24291881,Entire home/apt,Misericórdia,151,NaN,4,2.0,45.0
6010,10257022,52731804,Entire home/apt,Santa Maria Maior,21,NaN,2,0.0,46.0
6072,10413859,53629861,Entire home/apt,Arroios,70,NaN,4,1.0,58.0
6388,11255567,56974375,Entire home/apt,Arroios,8,NaN,2,1.0,52.0
9838,15963308,55556833,Entire home/apt,Santo António,0,NaN,3,2.0,97.0
11450,17848221,119340757,Entire home/apt,Misericórdia,1,NaN,4,1.0,45.0
13074,19225610,62988799,Entire home/apt,Misericórdia,0,NaN,2,0.0,74.0

Likewise, we can select those rows where a column is not null by using `notnull()`.

In [36]:
df[df.overall_satisfaction.notnull()].head()

,room_id,host_id,room_type,neighborhood,reviews,overall_satisfaction,accommodates,bedrooms,price
0,6499,14455,Entire home/apt,Belém,8,5.0,2,1.0,57.0
1,17031,66015,Entire home/apt,Alvalade,0,0.0,2,1.0,46.0
2,25659,107347,Entire home/apt,Santa Maria Maior,63,5.0,3,1.0,69.0
3,29248,125768,Entire home/apt,Santa Maria Maior,225,4.5,4,1.0,58.0
4,29396,126415,Entire home/apt,Santa Maria Maior,132,5.0,4,1.0,67.0

An easy way to check if any column has null values is by using `df.notnull().all()` (all will return True only if all rows match the condition:

In [37]:
df.notnull().all()

room_id                  True
host_id                  True
room_type                True
neighborhood             True
reviews                  True
overall_satisfaction    False
accommodates             True
bedrooms                 True
price                    True
dtype: bool

So we see that the column overall_satisfaction has some null values on it

We can find those rows that have any null like this (any returns true if any value is true, and using axis=1 means we are checking rows instead of columns:

In [38]:
df[df.isnull().any(axis=1)]

,room_id,host_id,room_type,neighborhood,reviews,overall_satisfaction,accommodates,bedrooms,price
1189,1424459,7665008,Entire home/apt,Misericórdia,63,NaN,8,4.0,104.0
2259,3112523,15814568,Entire home/apt,Misericórdia,1,NaN,3,1.0,69.0
3031,4460918,6317960,Entire home/apt,Arroios,75,NaN,4,1.0,40.0
3574,5569600,24291881,Entire home/apt,Misericórdia,151,NaN,4,2.0,45.0
6010,10257022,52731804,Entire home/apt,Santa Maria Maior,21,NaN,2,0.0,46.0
6072,10413859,53629861,Entire home/apt,Arroios,70,NaN,4,1.0,58.0
6388,11255567,56974375,Entire home/apt,Arroios,8,NaN,2,1.0,52.0
9838,15963308,55556833,Entire home/apt,Santo António,0,NaN,3,2.0,97.0
11450,17848221,119340757,Entire home/apt,Misericórdia,1,NaN,4,1.0,45.0
13074,19225610,62988799,Entire home/apt,Misericórdia,0,NaN,2,0.0,74.0

# Isin

We can check if an element belongs to a python list like this:

In [39]:
"potato" in ["potato", "tomato", "lettuce"]

True

We can use a similar approach with pandas dataframes using `.isin`. For example, if we want to select those listings where the neighborhood is in a specific list we can do it like this:

In [40]:
favorite_neighbourhoods = ["Belém", "Parque das Nações"]

listings_i_like = df[df.neighborhood.isin(favorite_neighbourhoods)]

listings_i_like.head()

,room_id,host_id,room_type,neighborhood,reviews,overall_satisfaction,accommodates,bedrooms,price
0,6499,14455,Entire home/apt,Belém,8,5.0,2,1.0,57.0
52,105962,106839925,Entire home/apt,Parque das Nações,29,5.0,4,1.0,69.0
70,129822,639944,Private room,Parque das Nações,50,4.5,2,1.0,55.0
79,137434,671930,Entire home/apt,Parque das Nações,0,0.0,6,2.0,138.0
126,184888,887175,Entire home/apt,Parque das Nações,7,4.5,6,2.0,115.0

# Query

The method `.query` allows us to use SQL to select rows from a dataframe.

In [41]:
df.query("neighborhood=='Belém' and price>150")

,room_id,host_id,room_type,neighborhood,reviews,overall_satisfaction,accommodates,bedrooms,price
1406,1803927,9456814,Entire home/apt,Belém,0,0.0,6,3.0,173.0
1551,2127428,8810620,Entire home/apt,Belém,17,5.0,9,5.0,184.0
1767,2608025,9456814,Entire home/apt,Belém,0,0.0,10,2.0,288.0
1948,2945967,2083563,Entire home/apt,Belém,1,0.0,2,1.0,202.0
2021,2993599,15262252,Private room,Belém,0,0.0,2,1.0,404.0
2075,3024528,15263699,Entire home/apt,Belém,0,0.0,4,2.0,692.0
2502,3473364,3953109,Entire home/apt,Belém,0,0.0,5,3.0,209.0
2559,3566413,3455184,Entire home/apt,Belém,5,5.0,6,3.0,173.0
2883,4101878,21277737,Entire home/apt,Belém,0,0.0,4,2.0,230.0
3399,5245908,5776233,Entire home/apt,Belém,14,5.0,4,1.0,173.0
3603,5622549,29144581,Entire home/apt,Belém,0,0.0,2,1.0,230.0
4954,7773383,40890592,Entire home/apt,Belém,27,4.5,6,3.0,173.0
8913,14711737,6316416,Entire home/apt,Belém,1,0.0,4,2.0,173.0
9290,15235859,96857687,Entire home/apt,Belém,0,0.0,3,1.0,231.0
9314,15272166,17263208,Entire home/apt,Belém,1,0.0,6,4.0,288.0
9539,15556702,100150750,Entire home/apt,Belém,0,0.0,4,2.0,231.0
10825,17228964,101182323,Entire home/apt,Belém,2,0.0,16,7.0,260.0
12181,18461428,115620308,Private room,Belém,2,0.0,10,2.0,208.0

## Filtering based on datatypes

In [ ]:
df.dtypes

We can use the method `select_dtypes` to select those columns that have specific types. 

For example, if we want to select only the columns that are floats, we can do:

In [ ]:
df.select_dtypes(include=[float]).head()

We can also use the parameter `exclude` to filter excluding certain data types. 

For example, if we want to exclude those columns that are python objects (and strings are objects), we can do so like:

In [ ]:
df.select_dtypes(exclude=[object]).head()